name: GitHub Actions 시작하기

# 언제 실행할 것인가?
on: [push]

# 어떤 일을 할 것인가?
jobs:
  say-hello:
    runs-on: ubuntu-latest  # 리눅스 가상 컴퓨터를 빌려 씀
    
    steps:
      - name: 인사하기
        run: echo "GitHub Actions가 성공적으로 실행되었습니다!"
